# -*- coding: utf-8 -*-
"""Transcripts

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WlENoGxxxHP1mWF5mivmDZ9UmCU7vCea
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install git+https://github.com/openai/whisper.git
!sudo apt update && sudo apt install ffmpeg

import os
import whisper

# 1. Load the model ONCE (saves massive time on multiple files)
print("Loading Whisper model into GPU (this takes 10 seconds)...")
model = whisper.load_model("medium") # Change "medium" to "small" here if you want it 3x faster

calls_dir = "/content/drive/MyDrive/Calls"
transcripts_dir = "/content/drive/MyDrive/Transcripts"
os.makedirs(transcripts_dir, exist_ok=True)

for filename in os.listdir(calls_dir):
    if filename.endswith((".mp3", ".wav", ".m4a", ".mp4")):
        file_path = os.path.join(calls_dir, filename)
        print(f"Transcribing {filename}...")

        # 2. Transcribe the audio
        result = model.transcribe(file_path)

        # 3. Save the text to a .txt file
        txt_filename = os.path.splitext(filename)[0] + ".txt"
        txt_path = os.path.join(transcripts_dir, txt_filename)

        with open(txt_path, "w", encoding="utf-8") as f:
            f.write(result["text"])

        # 4. Delete the original audio file
        os.remove(file_path)
        print(f"Success: Saved transcript and deleted {filename}\n")

print("Batch processing complete!")

